### PR TITLE
fix: using compareCommits for push event commit query

### PR DESCRIPTION
**Pull request by Brian-Triplett**
To actually resolve https://github.com/wagoid/commitlint-github-action/issues/752. 

This logic uses the `before` and `after` shas in the push event with the [compareCommits](https://octokit.github.io/rest.js/v21/#repos-compare-commits) REST resource in OctoKit to get a list of commits between two shas. This should accomplish getting the commits included from an incoming push to a given `ref`

### CODE REVIEW

**Comment by Brian-Triplett** [comment]
@wagoid I tested this locally with something like the following and it all seemed to work out. Let me know what you think!

```node
const github = require('@actions/github')

async function run() {
  const octokit = github.getOctokit(process.env.GITHUB_TOKEN)

  // You can also pass in additional options as a second parameter to getOctokit
  // const octokit = github.getOctokit(myToken, {userAgent: "MyActionVersion1"});

  const { data: compareCommits } = await octokit.rest.repos.compareCommits({
    owner: 'wagoid',
    repo: 'commitlint-github-action',
    base: 'baa1b236f990293a1b2d94c19e41c2313a85e749',
    head: '0de15449e923d75a908bd7ab4e89c4e69af9ab1f',
    per_page: 100,
  })

  console.log(compareCommits.commits)
}

run()
```

**Comment by Brian-Triplett** [comment]
hey @wagoid wanted to know if you had any questions or issues with this PR. This would help us out a lot and I'd rather not use our fork of this action if possible.

**Comment by wagoid** [comment]
Thanks @Brian-Triplett! Sorry for the delay, I could only have a look at this now.
Could you add a logic to handle times when the `before` is `0000000000000000000000000000000000000000`? This happens in the first push, that's why we had a failure in the job of your PR. I've added a log [here](https://github.com/wagoid/commitlint-github-action/actions/runs/10688183048/job/29627478915?pr=803) to demonstrate this happening:
```
before: 0000000000000000000000000000000000000000, after: 6d40f76ad6ef9b46be43ce925b1a1bc34c703b9d
```

In this case, I believe we should fallback to the commits coming from `eventContext` like it was before 💭

**Comment by wagoid** [comment]
In this PR you can better see this issue happening only in the first push: https://github.com/wagoid/commitlint-github-action/pull/803

**Comment by Brian-Triplett** [comment]
@wagoid just pushed up the change to handle the first push scenario. Let me know what you think!

**Review by wagoid — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
