### PR TITLE
build: upgrade base Docker image to prevent security vulnerability

### PR DESCRIPTION
**Pull request by diogokiss**
According to Snyk.io, the currently used base Docker image has 19 security
vulnerabilities (13 high).
https://snyk.io/test/docker/node%3A16.5.0-alpine3.14

On the other hand, the image `node:16.14.2-alpine3.14` has no known security
vulnerabilies.

https://snyk.io/test/docker/node%3A16.14.2-alpine3.14

This commit upgrades the image to fix the above mentioned issues.

### CODE REVIEW

**Comment by diogokiss** [comment]
Hi, @wagoid! 🇧🇷 👋 
I'm not really sure what the error with the failing job is about.
I mean, it is complaining about some permissions, but I'm not sure how to debug it.
If there is anything I can help with, please, let me know.

**Comment by diogokiss** [comment]
@wagoid, I think I fixed the Node version-related error. However, the error with regard to the unsafe repository seems to be related to this issue.
https://github.com/actions/checkout/issues/760

Apparently, there are 2 options to work around the problem:
* [Solution 1 - pre git v2.35.2](https://github.com/actions/checkout/issues/760#issuecomment-1097519290)
* [Solution 2 - git v2.35.2 onwards](https://github.com/actions/checkout/issues/760#issuecomment-1097501613)

**Comment by jdbruijn** [comment]
Yeah good one. Feel free to add the seconds solution, so `git config --global --add safe.directory /github/workspace` to the commitment workflow. As this is running in the action I'm guessing the `git` version to be latest, or at least near latest and that is also what the error log is suggesting 😄

**Comment by wagoid** [comment]
Hi @diogokiss! 🇧🇷 👋 🎉 
Thank you for the contribution! Agreed, as @jdbruijn said second option shouold probably be the right one 🚀

**Comment by wagoid** [comment]
Just noticed this issue was already present before your PR, so I created another one that fixes it: https://github.com/wagoid/commitlint-github-action/pull/411. Turns out `actions/checkout` was already applying the `safe.directory` in latest version but we needed to do something different for this action. The PR description explains everything. 

@diogokiss once you sync with origin the issue should be gone 🚀

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Maybe change it to the latest LTS, 16.15.0?

**Comment by wagoid** [comment]
@Fdawgs thanks for the suggestion! I'll update the dependabot config to also include `Dockerfile` so that we can more easily keep things up to date

**Pull request merged**
