### PR TITLE
fix(deps): udpate commitlint monorepo to v12

### LINKED ISSUE #97: deps: update @commitlint monrepo
@wagoid Regarding the `@commitlint` monorepo update, is it okay for you to update to v12 in one go or do you prefer to update to v11 first separately?

 As you've indicated they're breaking changes for this as well, so I suggest the following commit message.
 
 ```
  fix(deps): udpate commitlint monorepo to v12
  
  BREAKING CHANGES: Remove support for lerna v2 and change the order of the `extends` resolution from right-to-left to left-to-right.  
  ```

### PR DESCRIPTION
**Pull request by jdbruijn**
BREAKING CHANGE: Remove support for lerna v2 and change the order of the `extends` resolution from right-to-left to left-to-right.

Closes #97.

### CODE REVIEW

**Comment by jdbruijn** [comment]
The tests fails on both tests that use lerna , I haven't had time to look at it yet and I'm not familiar with the tests. @wagoid could you perhaps have a look at why these tests are failing?

**Comment by jdbruijn** [comment]
Okay, had a more in-depth look and it has to do with a change in `config-lerna-scopes`. If I revert the following, the tests pass.

https://github.com/conventional-changelog/commitlint/pull/2149/files#diff-4f14fb88e35cc639cdad864e486fcf813d5905ce3a4df8e250acd1e0fb9a5769R21-R34

**Comment by jdbruijn** [comment]
I've got the fix too. I'll update this PR within an hour.

**Review by wagoid — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
