### PR TITLE
README: Add a link to the commitlink project

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Review by jdbruijn — CHANGES_REQUESTED** [review]
I'd argue it should link to https://commitlint.js.org/#/, which is their main page as far as I know.

**Review by jdbruijn — APPROVED** [review]

**Review by wagoid — CHANGES_REQUESTED** [review]
Thanks for the contribution! One small detail, your commit message needs to have a valid subject. So instead of `README:` you can use `docs:` or `docs(README):`
You can see more details about the lint failure here: https://github.com/wagoid/commitlint-github-action/pull/152/checks?check_run_id=2499490935

**Comment by wagoid** [comment]
Sorry @sschuberth one more rule that I forgot in my suggestion: https://github.com/wagoid/commitlint-github-action/pull/152/checks?check_run_id=2499607746
So we need to replace by `docs(readme)`

**Comment by sschuberth** [comment]
> So we need to replace by `docs(readme)`

Done.

**Comment by wagoid** [comment]
Last one! `add` instead of `Add` haha

**Comment by sschuberth** [comment]
> Last one! `add` instead of `Add` haha

Already did that in parallel. Actually, this was a nice showcase, and probably showed me that these conventions are not for us 😉

**Comment by wagoid** [comment]
@sschuberth you can configure them, and remove whatever conventions you think is not fit for you. For example, in the company I work we allow any scope case so that we can put jira tickets in the scope. You can set your commitlint config file to make things loose as you want 🚀

**Review by wagoid — APPROVED** [review]

**Pull request merged**
